import { type IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiAstro,
  SiRemix,
  SiNuxt,
  SiGatsby,
  SiEmberdotjs,
  SiPreact,
  SiJquery,
  // Styling
  SiTailwindcss,
  SiBootstrap,
  SiSass,
  SiStyledcomponents,
  SiMui,
  // Build tools
  SiWebpack,
  SiVite,
  SiRollupdotjs,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiTurborepo,
  SiNpm,
  SiYarn,
  SiPnpm,
  // UI/viz
  SiThreedotjs,
  SiD3,
  SiChartdotjs,
  SiStorybook,
  // State/data
  SiRedux,
  SiMobx,
  SiGraphql,
  SiApollographql,
  // Desktop/mobile
  SiElectron,
  SiTauri,
  SiFlutter,
  SiIonic,
  SiCapacitor,
  // Runtimes
  SiNodedotjs,
  SiBun,
  SiDeno,
  // Backend frameworks
  SiExpress,
  SiFastify,
  SiNestjs,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiSpring,
  SiSpringboot,
  SiLaravel,
  SiRubyonrails,
  SiPhoenixframework,
  SiKoa,
  SiCelery,
  // Languages
  SiJavascript,
  SiTypescript,
  SiPython,
  SiGo,
  SiRust,
  SiCplusplus,
  SiPhp,
  SiRuby,
  SiSwift,
  SiKotlin,
  SiDart,
  SiScala,
  SiElixir,
  SiHaskell,
  SiLua,
  SiDotnet,
  // Databases
  SiMysql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiMariadb,
  SiApachecassandra,
  SiElasticsearch,
  SiNeo4J,
  SiInfluxdb,
  SiPlanetscale,
  SiSupabase,
  // ORMs / query
  SiPrisma,
  SiDrizzle,
  SiSequelize,
  // Cloud
  SiGooglecloud,
  SiDigitalocean,
  SiHeroku,
  SiVercel,
  SiNetlify,
  SiCloudflare,
  // DevOps
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiAnsible,
  SiJenkins,
  SiGitlab,
  SiCircleci,
  SiNginx,
  // Dev tools
  SiGit,
  SiGithub,
  SiBitbucket,
  SiJira,
  SiLinear,
  SiNotion,
  SiSlack,
  SiFigma,
  SiPostman,
  SiInsomnia,
  // Testing
  SiJest,
  SiVitest,
  SiCypress,
  SiSelenium,
  // Messaging/queues
  SiApachekafka,
  SiRabbitmq,
  SiNatsdotio,
  // AI/ML
  SiTensorflow,
  SiPytorch,
  SiOpenai,
  SiHuggingface,
  SiLangchain,
  SiPandas,
  SiNumpy,
  SiJupyter,
  // Other platforms
  SiLinux,
  SiUbuntu,
  SiWordpress,
  SiShopify,
  SiStripe,
  SiFirebase,
  SiAuth0,
  SiGnubash,
  SiCockroachlabs,
  SiPuppeteer,
} from "react-icons/si";
import { FaAws, FaJava } from "react-icons/fa";
import { FaMicrosoft } from "react-icons/fa6";
import { BiLogoPostgresql } from "react-icons/bi";

export const SKILL_ICONS: Record<string, IconType | undefined> = {
  // Frontend frameworks
  react: SiReact,
  "react.js": SiReact,
  reactjs: SiReact,
  "next.js": SiNextdotjs,
  nextjs: SiNextdotjs,
  nextjss: SiNextdotjs,
  "vue.js": SiVuedotjs,
  vuejs: SiVuedotjs,
  vue: SiVuedotjs,
  angular: SiAngular,
  svelte: SiSvelte,
  sveltekit: SiSvelte,
  astro: SiAstro,
  remix: SiRemix,
  "nuxt.js": SiNuxt,
  nuxtjs: SiNuxt,
  nuxt: SiNuxt,
  gatsby: SiGatsby,
  ember: SiEmberdotjs,
  "ember.js": SiEmberdotjs,
  preact: SiPreact,
  jquery: SiJquery,
  // Styling
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  "tailwind css": SiTailwindcss,
  bootstrap: SiBootstrap,
  sass: SiSass,
  scss: SiSass,
  "styled components": SiStyledcomponents,
  styledcomponents: SiStyledcomponents,
  mui: SiMui,
  "material ui": SiMui,
  materialui: SiMui,
  // Build tools
  webpack: SiWebpack,
  vite: SiVite,
  rollup: SiRollupdotjs,
  babel: SiBabel,
  eslint: SiEslint,
  prettier: SiPrettier,
  turborepo: SiTurborepo,
  npm: SiNpm,
  yarn: SiYarn,
  pnpm: SiPnpm,
  // UI/viz
  "three.js": SiThreedotjs,
  threejs: SiThreedotjs,
  "d3.js": SiD3,
  d3: SiD3,
  "chart.js": SiChartdotjs,
  chartjs: SiChartdotjs,
  storybook: SiStorybook,
  // State/data
  redux: SiRedux,
  mobx: SiMobx,
  graphql: SiGraphql,
  apollo: SiApollographql,
  // Desktop/mobile
  electron: SiElectron,
  tauri: SiTauri,
  flutter: SiFlutter,
  ionic: SiIonic,
  capacitor: SiCapacitor,
  // Runtimes
  "node.js": SiNodedotjs,
  nodejs: SiNodedotjs,
  node: SiNodedotjs,
  bun: SiBun,
  deno: SiDeno,
  // Backend frameworks
  express: SiExpress,
  "express.js": SiExpress,
  expressjs: SiExpress,
  fastify: SiFastify,
  nestjs: SiNestjs,
  "nest.js": SiNestjs,
  django: SiDjango,
  flask: SiFlask,
  fastapi: SiFastapi,
  spring: SiSpring,
  "spring boot": SiSpringboot,
  springboot: SiSpringboot,
  laravel: SiLaravel,
  rails: SiRubyonrails,
  "ruby on rails": SiRubyonrails,
  rubyonrails: SiRubyonrails,
  phoenix: SiPhoenixframework,
  koa: SiKoa,
  "koa.js": SiKoa,
  celery: SiCelery,
  // Languages
  javascript: SiJavascript,
  js: SiJavascript,
  typescript: SiTypescript,
  ts: SiTypescript,
  python: SiPython,
  go: SiGo,
  golang: SiGo,
  rust: SiRust,
  "c++": SiCplusplus,
  cpp: SiCplusplus,
  php: SiPhp,
  ruby: SiRuby,
  swift: SiSwift,
  kotlin: SiKotlin,
  dart: SiDart,
  scala: SiScala,
  elixir: SiElixir,
  haskell: SiHaskell,
  lua: SiLua,
  java: FaJava,
  ".net": SiDotnet,
  dotnet: SiDotnet,
  "c#": SiDotnet,
  csharp: SiDotnet,
  // Databases
  postgres: BiLogoPostgresql,
  postgresql: BiLogoPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  mongo: SiMongodb,
  redis: SiRedis,
  sqlite: SiSqlite,
  mariadb: SiMariadb,
  cassandra: SiApachecassandra,
  elasticsearch: SiElasticsearch,
  neo4j: SiNeo4J,
  influxdb: SiInfluxdb,
  planetscale: SiPlanetscale,
  supabase: SiSupabase,
  // ORMs
  prisma: SiPrisma,
  drizzle: SiDrizzle,
  sequelize: SiSequelize,
  // Cloud
  aws: FaAws,
  "amazon web services": FaAws,
  gcp: SiGooglecloud,
  "google cloud": SiGooglecloud,
  "google cloud platform": SiGooglecloud,
  azure: FaMicrosoft,
  "microsoft azure": FaMicrosoft,
  digitalocean: SiDigitalocean,
  "digital ocean": SiDigitalocean,
  heroku: SiHeroku,
  vercel: SiVercel,
  netlify: SiNetlify,
  cloudflare: SiCloudflare,
  // DevOps
  docker: SiDocker,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  terraform: SiTerraform,
  ansible: SiAnsible,
  jenkins: SiJenkins,
  gitlab: SiGitlab,
  circleci: SiCircleci,
  nginx: SiNginx,
  // Dev tools
  git: SiGit,
  github: SiGithub,
  bitbucket: SiBitbucket,
  jira: SiJira,
  linear: SiLinear,
  notion: SiNotion,
  slack: SiSlack,
  figma: SiFigma,
  postman: SiPostman,
  insomnia: SiInsomnia,
  // Testing
  jest: SiJest,
  vitest: SiVitest,
  cypress: SiCypress,
  selenium: SiSelenium,
  // Messaging/queues
  kafka: SiApachekafka,
  "apache kafka": SiApachekafka,
  rabbitmq: SiRabbitmq,
  nats: SiNatsdotio,
  // AI/ML
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  openai: SiOpenai,
  "hugging face": SiHuggingface,
  huggingface: SiHuggingface,
  langchain: SiLangchain,
  pandas: SiPandas,
  numpy: SiNumpy,
  jupyter: SiJupyter,
  // Other platforms
  linux: SiLinux,
  ubuntu: SiUbuntu,
  wordpress: SiWordpress,
  shopify: SiShopify,
  stripe: SiStripe,
  firebase: SiFirebase,
  auth0: SiAuth0,
  bash: SiGnubash,
  shell: SiGnubash,
  cockroachdb: SiCockroachlabs,
  puppeteer: SiPuppeteer,
  bullmq: undefined,
};
